MvcCoreConsumoApiEmpleados2022/Models/ErrorViewModel.cs
using System;

namespace MvcCoreConsumoApiEmpleados2022.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCoreConsumoApiEmpleados2022/Controllers/EmpleadosController.cs
using LibrariesEmpleado;
using Microsoft.AspNetCore.Mvc;
using MvcCoreConsumoApiEmpleados2022.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcCoreConsumoApiEmpleados2022.Controllers
{
    public class EmpleadosController : Controller
    {
        private ServiceApiEmpleados service;

        public EmpleadosController(ServiceApiEmpleados service)
        {
            this.service = service;
        }

        public async Task<IActionResult> Index()
        {
            List<string> oficios = await this.service.GetOficiosAsync();
            List<Empleado> empleados = 
                await this.service.GetEmpleadosAsync();
            ViewData["OFICIOS"] = oficios;
            return View(empleados);
        }

        [HttpPost]
        public async Task<IActionResult> Index(string oficio)
        {
            List<string> oficios = await this.service.GetOficiosAsync();
            List<Empleado> empleados =
                await this.service.GetEmpleadosOficioAsync(oficio);
            ViewData["OFICIOS"] = oficios;
            return View(empleados);
        }
    }
}

MvcCoreConsumoApiEmpleados2022/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcCoreConsumoApiEmpleados2022.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MvcCoreConsumoApiEmpleados2022.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCoreConsumoApiEmpleados2022/Views/Empleados/Index.cshtml
@model List<LibrariesEmpleado.Empleado>

@{ 
    List<string> oficios = ViewData["OFICIOS"] as List<string>;
}

<h1>Consumo Api Empleados Servidor C#</h1>

<form method="post">
    <label>Oficios: </label>
    <select name="oficio" class="form-control">
        @foreach (string ofi in oficios)
        {
            <option value="@ofi">@ofi</option>
        }
    </select>
    <button type="submit" class="btn btn-info">
        Mostrar empleados
    </button>
</form>
<hr/>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Apellido</th>
            <th>Oficio</th>
            <th>Salario</th>
            <th>Departamento</th>
        </tr>
    </thead>
    <tbody>
        @foreach (LibrariesEmpleado.Empleado emp in Model)
        {
            <tr>
                <td>@emp.Apellido</td>
                <td>@emp.Oficio</td>
                <td>@emp.Salario</td>
                <td>@emp.IdDepartamento</td>
            </tr>
        }
    </tbody>
</table>

MvcCoreConsumoApiEmpleados2022/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcCoreConsumoApiEmpleados2022/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreConsumoApiEmpleados2022</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCoreConsumoApiEmpleados2022</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Empleados"
                               asp-action="Index"
                               class="nav-link">
                                Empleados API
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MvcCoreConsumoApiEmpleados2022 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>